### ISSUE TITLE
Doc Request : Simple Blog Demo

### ISSUE THREAD

**Issue by king009** [bkader/skeleton#1]
How about creating a simple blog module demo?

It took me 10 minutes to figure out from where is the view called. N still can't figure out how header and footer got connected to the template. :smile: 

Akshit

**Comment by bkader** [comment]
Hi there.
You can check the default theme to see how it Ian calling views.  
The provided theme library handles headers and footers. They can be overridden by creating a header.php and footer.php files within theme’s folder. Even if you don’t have them the library will still output a default header and footer.  

I will create a blog example as soon as possible. You can find temporary documentation, see link next to repository description.

**Comment by bkader** [comment]
This will be the documentation: [Link](https://goo.gl/Wjj72j)
