### ISSUE TITLE
Language Files Edit Functionality inside Admin Panel

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#11]
First of all I like your way of file system for multilanguage issue. 
I think that editing language files inside admin panel can be very useful,

A function can search all language terms or you provide only english and function reads from there and serve them to admin page. But this way maybe it is possible to forget any language term.
What is going to happen when you add a new term to any language file you need to manually update all other language files.
 
In my point of view storing language terms inside database as serialized array and saving from admin panel automatically will prevent any terms lack.

If you already have a solution for this issue please notice. Thanks

**Comment by bkader** [comment]
I wanted to implement a function to translate/add/delete language lines but I dropped it as there was more urgent things to deal with. This feature will be implemented as well.
