### ISSUE TITLE
Multisite System

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#12]
Do you plan to develop a CMS system like wordpress does ***but very different from wordpress.***

Wordpress is consuming very much ram and overusing database automatically inserting revision posts.
There are some solutions for this issue but still I do not like wordpress. I am **Codeigniterist**.

If you have plan to make CMS integrated into admin I will wait or else I will think another solution (maybe a module or plugin). But your coding is very nice If you will do it, it worths waiting :)

**Comment by bkader** [comment]
I have already developed a quick (imperfect) CMS module for version 1, I will soon adapt it to version 2 and it will be shared.
