### ISSUE TITLE
Database backup / restore

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#13]
Do you have plan to make an admin page which backs up and restores database manually / daily / monthly. 
It would be nice to have this function. 

I have seen this functionality on [ci_bootstrap_3](https://github.com/waifung0207/ci_bootstrap_3).
Back up function is working like a charm but restore doesn't work on this. Still it can be used and fixed.

![e391792b-7dbd-4ec6-809b-255dbd7b1fb6](https://user-images.githubusercontent.com/16270198/41980944-6f346cce-7a30-11e8-9ae0-cbd9de04b299.png)

If you havent seen ci_bootstrap_3 before, it has very useful functions. It can give you other useful ideas.

**Comment by bkader** [comment]
This will be implented soon, thanks for your precious suggestion.
