### ISSUE TITLE
Front end Multi Language Url

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#14]
Isn't it better to have url per language which will effect site SEO better
**like this:**
dev.skeleton.com/en/*
dev.steleton.com/fr/*

**Comment by bkader** [comment]
SEO no longer care about language in URL.. In fact, if your site is multilingual, SEO will use most of time the english version, and search engines will use user's supported language. i.e: If a user is using google.es, results from your site will appear in spanish ... etc
