### ISSUE TITLE
Social Login Functionality

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#15]
Hi @bkader,
Do you have plan to integrate social login functionality for this awesome software?
If so I have a package which already has this functionality. I can share.
If you are interested please inform me.

or you can consider [CodeIgniter-HybridAuth](https://github.com/ApacheEx/CodeIgniter-HybridAuth)
It has

**Comment by bkader** [comment]
This feature is planned .. I prefered not to include it to allow usage of modules/plugins that provide such functionality.
