### ISSUE TITLE
Front End User Profile and Settings Links doesn't Work

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#16]
When I click this links it goes to 
http://localhost/ci-skeleton/username and http://localhost/ci-skeleton/settings links.
They don't work.

![screenshot-2018-6-27 skeleton](https://user-images.githubusercontent.com/16270198/41985698-c1afb36c-7a3c-11e8-8a2a-6838ca24bf4f.png)

**Comment by bkader** [comment]
Indeed, this was left empty to allow you develop those pages using the module/controller you want ..
