### ISSUE TITLE
Admin Login Page: Message: Argument 1 passed to Theme::body_class()

### ISSUE THREAD

**Issue by ghost** [bkader/skeleton#17]
When I logged in as **user** (not admin) and directly visit http://localhost/skeleton/admin page, as natural redirects to http://localhost/skeleton/admin/login?next=admin page and gives the error below.
I think I see this because I use PHP 5.6 on local machine. But Main issue is regular user's viewing admin login page should be an unwanted activity. 
I suggest seperating admin login and regular user login. Or at least (maybe better) when a regular user is logged in wants to see http://localhost/skeleton/admin page, system should redirect that user to his profile page. This would be nicer. Otherwise If he or she logins via admin/login form, maybe there will be two sessions. So before logining as admin, user should logout.

```
A PHP Error was encountered

Severity: 4096

Message: Argument 1 passed to Theme::body_class() must be an instance of string, string given, called in D:\wamp\www\ci-skeleton\skeleton\controllers\admin\Login.php on line 137 and defined

Filename: libraries/Theme.php

Line Number: 1994

Backtrace:

File: D:\wamp\www\ci-skeleton\skeleton\third_party\theme\libraries\Theme.php
Line: 1994
Function: _error_handler

File: D:\wamp\www\ci-skeleton\skeleton\controllers\admin\Login.php
Line: 137
Function: body_class

File: D:\wamp\www\ci-skeleton\application\bootstrap.php
Line: 95
Function: require_once

File: D:\wamp\www\ci-skeleton\index.php
Line: 368
Function: require_once
```

![screenshot-2018-6-27 sign in skeleton skeleton](https://user-images.githubusercontent.com/16270198/41986257-4aa92a94-7a3e-11e8-9be1-da7febdd0583.png)

**Comment by bkader** [comment]
This will be fixed on the next update (2.1.6) or you can download the develop branch as it is always up to date until the next release.
