### ISSUE TITLE
Feature Request: Search functionality.

### ISSUE THREAD

**Issue by king009** [bkader/skeleton#3]
It would be great if we have something dedicated for searching our entities/objects. 😃

**Comment by bkader** [comment]
Search feature has been added to almost all tables except **options**. As of the next release (**v1.3.0**), it should be possible to perform complex queries. Here are some examples:

```php
// WHERE subtype = post AND name LIKE %first% AND name NOT LIKE %second%
$this->kbcore->objects->find(array(
    'subtype' => 'post',
    'name' => array('first', '!second')
));

// WHERE subtype = post AND name NOT LIKE %first% AND name NOT LIKE %second%
$this->kbcore->objects->find(array(
    'subtype' => 'post',
    '!name' => array('first', 'second')
));

// WHERE subtype = post AND name LIKE %first% OR name LIKE %second%
// AND name NOT LIKE foo AND name NOT LIKE bar
$this->kbcore->objects->find(array(
    'subtype' => 'post',
    'name' => array('first', 'second')
   'or:name' => array('foo', 'bar')
));
```

It will be possible to use the following commands in case of single => single:

* **or:\_field_**: to generate *or_where* or *or_like*.
* **or:!\_field_**: to generate *or_where_not* or *or_not_like*.
* **!\_field_**: to generate *where* (!=) or *not_like*.
* **\_field_**: to generate *where* or *like*.

In case of single => array

* **or:\_field_**: to generate *or_where_in*0
* **or:!\_field_**: to generate *or_where_not_in*.
* **!\_field_**: to generate *where_not_in*.
* **\_field_**: to generate *where_in*.

**Comment by king009** [comment]
Fair enough, **options** should not even have the search feature.

**Comment by bkader** [comment]
The search feature is available on the [develop](https://github.com/bkader/skeleton) and [master](https://github.com/bkader/skeleton/tree/master) branches. Once the full code revisited and checked, everything will be merged into the [stable](https://github.com/bkader/skeleton/tree/stable) branch and a new release will be created.

**Comment by bkader** [comment]
Feature added.
