### ISSUE TITLE
Bug: Typo error.

### ISSUE THREAD

**Issue by king009** [bkader/skeleton#4]
https://github.com/bkader/skeleton/blob/19b4711f67f833dd155b1198dfefe720f8758c5e/src/skeleton/libraries/Kbcore/drivers/Kbcore_relations.php#L107

Please change empt to empty. Also at line # 125.

https://github.com/bkader/skeleton/blob/19b4711f67f833dd155b1198dfefe720f8758c5e/src/skeleton/libraries/Kbcore/drivers/Kbcore_relations.php#L144
Also, $dat should be $data

**Comment by bkader** [comment]
Thanks for reporting this! I fixed it locally and it will be available on the next push.  
A lot of code reforming has been done for better performance ... You will see, maybe, later tonight (*it is 19:53 here*).

**Comment by bkader** [comment]
Typos were fixed on both [develop](https://github.com/bkader/skeleton) and [master](https://github.com/bkader/skeleton/tree/master) branches. Once the full code revisited and checked, everything will be merged into the [stable](https://github.com/bkader/skeleton/tree/stable) branch and a new release will be created.

**Comment by bkader** [comment]
Typos fixed and a new release is out: [1.3.0](https://github.com/bkader/skeleton/releases/tag/1.3.0)
