### ISSUE TITLE
PHP before 5.5 support

### ISSUE THREAD

**Issue by balajtii** [bkader/skeleton#6]
"Can't use method return value in write context" error.

And this cause : 
"empty() needs to access the value by reference (in order to check whether that reference points to something that exists), and PHP before 5.5 didn't support references to temporary values returned from functions."

So I have to extract the checkable value, and do the check on the variable.

example KB_Lang 133 row:
$idiom = empty($this->config->item('language')) ? $this->fallback : $this->config->item('language');

to this:
$language = $this->config->item('language');
$idiom = empty($language) ? $this->fallback : $language;

**Comment by balajtii** [comment]
Class 'Self' not found 
src/skeleton/libraries/Plugins.php 95

replace
self::$_instance = new Self;
to
self::$_instance = new self;

**Comment by balajtii** [comment]
src/skeleton/modules/language/controllers/Language.php  line 85

function switch ...

Where a "switch" is a reserved word and get parse error

**Comment by bkader** [comment]
Indeed, [it is](http://php.net/manual/en/reserved.keywords.php) .. What should I use instead? **change**?

**Comment by balajtii** [comment]
I think the change is a good alternative

**Comment by bkader** [comment]
Changed, it will be available on the next version release. Thanks @balajtii

**Comment by bkader** [comment]
I close this issue because just like Codeigniter, this project requires at least PHP 5.6.

**Comment by ghost** [comment]
Requiring at least PHP 5.6 is very nice. Because as you say, Codeigniter requires at least 5.6
