### ISSUE TITLE
Call to protected method KB_Controller::check_captcha()

### ISSUE THREAD

**Issue by 666bits** [bkader/skeleton#7]
Wherever the captcha check is used as callback for form rules `callback_check_captcha` it triggers this issue:

`Call to protected method KB_Controller::check_captcha() from context 'CI_Form_validation'`

I believe it is better to change their access to `public` instead of `protected`.

**Comment by bkader** [comment]
Thanks for reporting this. This was fixed and can be found [here](https://github.com/bkader/skeleton/releases/tag/1.5.1).
