### ISSUE TITLE
html_class filter not working correctly.

### ISSUE THREAD

**Issue by mavericksy** [bkader/skeleton#8]
Seems like the html_class filter does nothing.

The array passed to the callback is null for the filter but a long list of classes is still appended in the theme html tag.

**Comment by bkader** [comment]
I just got home, I will check the issue in few minutes and keep you updated. Thank you for reporting this.

**Comment by bkader** [comment]
Hi again,  
I just tested both `html_class` and `body_class`, they both work just fine. See below how I did the test:

```php
// html_class.
add_filter('html_class', function($classes) {
    $classes[] = 'test1';
    $classes[] = 'test2';
    return $classes;
});

// body_class.
add_filter('body_class', function($classes) {
    $classes[] = 'test1';
    $classes[] = 'test2';
    return $classes;
});
```

The final result was:

```html
<html class="test1 test2 test3" lang="en">
...
<body class=".... test1 test2 test3">
```

**Comment by mavericksy** [comment]
The jQuery and Modernizr scripts were adding html tag classes. 
Couldn't remove those with the filter. That was the problem.
remove_script() helped.
