### ISSUE TITLE
styles is tried to load via http nonetheless the site is https causing Mixed Content

### ISSUE THREAD

**Issue by redaxhu** [bkader/skeleton#9]
I have tested master 2.1. 

in case the site is SSL, the styles is loaded via http
in Admin_Controller.php line 174 there is a hardcoded http in 
                $this->theme
                    ->no_extension()
                    ->add('css', admin_url('load/styles?load='.implode(',', $this->styles), 'http'), null, null, true);

this causes the implicite http loading of styles.
would you check this one please ?

**Comment by bkader** [comment]
Thanks for reporting this @redaxhu. Let me know if it was fixed please.
